name: CI

on:
  push:
    branches:
      - '*'  # Запускаем на push в любую ветку
  pull_request:
    branches:
      - '*'  # Запускаем на любой PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: tests
        run: |
          mypy --ignore-missing-imports fastapi_app/  # Запускаем тесты
          black fastapi_app/ # --check --diff fastapi_app/ 
          
      - name: test isort
        run:
          isort --check-only --profile black fastapi_app/

      - name: test flake8
        run:
          flake8 --extend-ignore E501 fastapi_app/
          
